spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/case_manage
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password:
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 500
          min-idle: 0
        shutdown-timeout: 0


server:
  port: 8083

