spring:
  datasource:
    username: root
    password: Weixiaolei123
    url: jdbc:mysql://nj-cynosdbmysql-grp-r87qqusx.sql.tencentcdb.com:20530/case_manage?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:

    date-format: yyyy-MM-dd HH:mm:ss  #时间戳统一转换为指定格式

    time-zone: GMT+8  # 时区修改为东8区 作者：CSLShare https://www.bilibili.com/read/cv16593259/ 出处：bilibili

  data:
    redis:
      host: localhost
      port: 6379
      password:
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 500
          min-idle: 0
        shutdown-timeout: 0


server:
  port: 8083

#mybatis-plus:
#  global-config:
#    db-config:
#      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

file-save-path: /uploadFile/